apiVersion: v1
kind: Service
metadata:
  name: sba-svc
  labels:
    app: sba-flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: sba-flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-deployment
  labels:
    app: sba-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sba-flask-app
  template:
    metadata:
      labels:
        app: sba-flask-app
    spec:
      containers:
      - name: sba-flask-app
        image: spadevapps/sba.kubernetes-cluster
        ports:
        - containerPort: 9090
